# Generated by Django 5.2 on 2025-12-30 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_reference', models.CharField(blank=True, help_text='Auto-generated unique contract reference', max_length=20, unique=True)),
                ('work_description', models.TextField(blank=True, help_text='Detailed description of work to be performed', null=True)),
                ('agreed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total agreed amount in IQD (required before acceptance)', max_digits=15, null=True)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent for reference only', max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate (IQD to USD) at contract creation', max_digits=10, null=True)),
                ('escrow_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount held in escrow in IQD', max_digits=15)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far in IQD', max_digits=15)),
                ('contract_duration', models.DateField(blank=True, help_text='Expected completion date', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Current contract status', max_length=50)),
                ('stage_number', models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 Stages'), (3, '3 Stages'), (4, '4 Stages'), (5, '5 Stages')], help_text='Number of payment stages for this contract', null=True)),
                ('client_accepted', models.BooleanField(db_index=True, default=False, help_text='Client has accepted the contract')),
                ('technician_accepted', models.BooleanField(db_index=True, default=False, help_text='Technician has accepted the contract')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Contract creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification timestamp')),
                ('client', models.ForeignKey(help_text='Client initiating the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.clientprofile')),
                ('technician', models.ForeignKey(help_text='Technician performing the work', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_number', models.PositiveIntegerField(help_text='Sequential stage number (1, 2, 3, etc.)')),
                ('stage_description', models.TextField(blank=True, help_text='Description of work for this stage')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount for this stage in IQD', max_digits=15)),
                ('deadline', models.DateField(blank=True, help_text='Target completion date for this stage', null=True)),
                ('is_approved_by_client', models.BooleanField(db_index=True, default=False, help_text='Client has approved completion of this stage')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When technician marked this stage as complete', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(help_text='Parent contract', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='contract.contract')),
                ('transaction', models.OneToOneField(blank=True, help_text='Associated payment transaction for this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_stage', to='accounts.wallettransaction')),
            ],
            options={
                'ordering': ['contract', 'stage_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeExtensionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_days', models.PositiveSmallIntegerField(help_text='Number of days requested (1-30)')),
                ('reason', models.TextField(help_text='Reason for requesting the extension')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the extension request', max_length=20)),
                ('client_response', models.TextField(blank=True, help_text="Client's response or rejection reason", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When client responded to the request', null=True)),
                ('contract', models.ForeignKey(help_text='Contract being extended', on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='contract.contract')),
                ('requested_by', models.ForeignKey(help_text='Technician requesting the extension', on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='accounts.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client'], name='contract_co_client__e84930_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['technician'], name='contract_co_technic_6d16cc_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_co_status_601477_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_accepted', 'technician_accepted'], name='contract_co_client__66f3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='contract_co_created_6430e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_deleted'], name='contract_co_is_dele_a4c522_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstage',
            index=models.Index(fields=['contract', 'stage_number'], name='contract_co_contrac_a78b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstage',
            index=models.Index(fields=['is_approved_by_client'], name='contract_co_is_appr_cd8c62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractstage',
            unique_together={('contract', 'stage_number')},
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['contract', 'status'], name='contract_ti_contrac_cfea5a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['requested_by', 'status'], name='contract_ti_request_11fc01_idx'),
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['created_at'], name='contract_ti_created_038dbe_idx'),
        ),
    ]
