# Generated by Django 5.2 on 2026-01-08 19:03

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_technicianprofile_job_title'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='contractstage',
            options={'ordering': ['contract', 'stage_number'], 'verbose_name': 'Contract Stage', 'verbose_name_plural': 'Contract Stages'},
        ),
        migrations.AlterModelOptions(
            name='timeextensionrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Time Extension Request', 'verbose_name_plural': 'Time Extension Requests'},
        ),
        migrations.RemoveIndex(
            model_name='contract',
            name='contract_co_is_dele_a4c522_idx',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='IQD', help_text='Currency code for agreed amount', max_length=3),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='timeextensionrequest',
            name='is_delete',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_reference',
            field=models.CharField(blank=True, help_text='Auto-generated unique contract reference (e.g., #A1B2C3D4E5F6)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate (IQD to USD) recorded at contract creation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid to technician so far in IQD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contractstage',
            name='stage_description',
            field=models.TextField(blank=True, help_text='Description of work and deliverables for this stage'),
        ),
        migrations.AlterField(
            model_name='timeextensionrequest',
            name='client_response',
            field=models.TextField(blank=True, help_text="Client's response comment or rejection reason", null=True),
        ),
        migrations.AlterField(
            model_name='timeextensionrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='timeextensionrequest',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_delete'], name='contract_co_is_dele_11c95e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstage',
            index=models.Index(fields=['created_at'], name='contract_co_created_753e9a_idx'),
        ),
    ]
