# Generated by Django 6.0 on 2025-12-28 15:29

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_technicianimage_options_and_more'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.PositiveIntegerField(help_text='Sequential stage number (1, 2, 3, etc.)')),
                ('stage_description', models.TextField(blank=True, help_text='Description of work for this stage')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount for this stage in IQD', max_digits=15)),
                ('deadline', models.DateField(blank=True, help_text='Target completion date for this stage', null=True)),
                ('is_approved_by_client', models.BooleanField(db_index=True, default=False, help_text='Client has approved completion of this stage')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When technician marked this stage as complete', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['contract', 'stage_number'],
            },
        ),
        migrations.CreateModel(
            name='TimeExtensionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_days', models.PositiveSmallIntegerField(help_text='Number of days requested (1-30)')),
                ('reason', models.TextField(help_text='Reason for requesting the extension')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', help_text='Current status of the extension request', max_length=20)),
                ('client_response', models.TextField(blank=True, help_text="Client's response or rejection reason", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When client responded to the request', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='contract',
            name='title',
        ),
        migrations.AddField(
            model_name='contract',
            name='agreed_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total agreed amount in IQD (required before acceptance)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='USD equivalent for reference only', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='client_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='Client has accepted the contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_duration',
            field=models.DateField(blank=True, help_text='Expected completion date', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_reference',
            field=models.CharField(blank=True, help_text='Auto-generated unique contract reference', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='escrow_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount held in escrow in IQD', max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate (IQD to USD) at contract creation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag'),
        ),
        migrations.AddField(
            model_name='contract',
            name='stage_number',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(2, '2 Stages'), (3, '3 Stages'), (4, '4 Stages'), (5, '5 Stages')], help_text='Number of payment stages for this contract', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='technician_accepted',
            field=models.BooleanField(db_index=True, default=False, help_text='Technician has accepted the contract'),
        ),
        migrations.AddField(
            model_name='contract',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount paid so far in IQD', max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='work_description',
            field=models.TextField(blank=True, help_text='Detailed description of work to be performed', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(help_text='Client initiating the contract', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.clientprofile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Contract creation timestamp'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Current contract status', max_length=50),
        ),
        migrations.AlterField(
            model_name='contract',
            name='technician',
            field=models.ForeignKey(help_text='Technician performing the work', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts.technicianprofile'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client_accepted', 'technician_accepted'], name='contract_co_client__66f3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['created_at'], name='contract_co_created_6430e0_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['is_deleted'], name='contract_co_is_dele_a4c522_idx'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='contract',
            field=models.ForeignKey(help_text='Parent contract', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='contractstage',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Associated payment transaction for this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_stage', to='accounts.wallettransaction'),
        ),
        migrations.AddField(
            model_name='timeextensionrequest',
            name='contract',
            field=models.ForeignKey(help_text='Contract being extended', on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='timeextensionrequest',
            name='requested_by',
            field=models.ForeignKey(help_text='Technician requesting the extension', on_delete=django.db.models.deletion.CASCADE, related_name='extension_requests', to='accounts.technicianprofile'),
        ),
        migrations.AddIndex(
            model_name='contractstage',
            index=models.Index(fields=['contract', 'stage_number'], name='contract_co_contrac_a78b5b_idx'),
        ),
        migrations.AddIndex(
            model_name='contractstage',
            index=models.Index(fields=['is_approved_by_client'], name='contract_co_is_appr_cd8c62_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractstage',
            unique_together={('contract', 'stage_number')},
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['contract', 'status'], name='contract_ti_contrac_cfea5a_idx'),
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['requested_by', 'status'], name='contract_ti_request_11fc01_idx'),
        ),
        migrations.AddIndex(
            model_name='timeextensionrequest',
            index=models.Index(fields=['created_at'], name='contract_ti_created_038dbe_idx'),
        ),
    ]
