# Generated by Django 6.0 on 2026-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_options_alter_contractstage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='exchange_rate',
        ),
        migrations.AddField(
            model_name='contract',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days for the project duration', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, help_text='Project start date provided by technician', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_duration',
            field=models.DateField(blank=True, help_text='Calculated deadline date (start_date + duration_days)', null=True),
        ),
    ]
