# Generated by ChatGPT on 2026-02-27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_exchange_rate_contract_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='client_platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-refundable client platform fee charged on contract activation', max_digits=15),
        ),
        migrations.AddField(
            model_name='contract',
            name='technician_platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Non-refundable technician platform fee charged on contract activation', max_digits=15),
        ),
    ]
