# Generated by Django 6.0 on 2026-02-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_contract_client_platform_fee_and_more'),
        ('wallet', '0002_delete_platformwallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractstage',
            name='transaction',
            field=models.OneToOneField(blank=True, help_text='Associated payment transaction for this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_stage', to='wallet.wallettransaction'),
        ),
    ]
