# Generated by Django 5.2.15 on 2026-06-14 12:34

import contract.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image_and_more'),
        ('contract', '0005_alter_contractstage_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='finalized_at',
            field=models.DateTimeField(blank=True, help_text='When the signed/final contract package was finalized', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='finalized_by',
            field=models.ForeignKey(blank=True, help_text='User who triggered finalization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('pending_signatures', 'Pending Signatures'), ('pending_finalization', 'Pending Finalization'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Current contract status', max_length=50),
        ),
        migrations.CreateModel(
            name='ContractVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField()),
                ('canonical_snapshot', models.JSONField(default=dict)),
                ('canonical_snapshot_hash', models.CharField(db_index=True, max_length=64)),
                ('is_frozen', models.BooleanField(db_index=True, default=True)),
                ('frozen_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='contract.contract')),
                ('frozen_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_contract_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signer_role', models.CharField(choices=[('client', 'Client'), ('technician', 'Technician')], db_index=True, max_length=20)),
                ('signed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('signature_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=500)),
                ('otp_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_signatures', to='accounts.otpverification')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='contract.contractversion')),
            ],
        ),
        migrations.CreateModel(
            name='ContractDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('draft_pdf', 'Draft PDF'), ('signed_pdf', 'Signed PDF')], db_index=True, max_length=20)),
                ('file', models.FileField(upload_to=contract.models.contract_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('mime_type', models.CharField(default='application/pdf', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_documents_created', to=settings.AUTH_USER_MODEL)),
                ('contract_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contract.contractversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAttestation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('attestation_hash', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('contract_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='contract.contractversion')),
            ],
        ),
        migrations.CreateModel(
            name='ContractAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_audit_events', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='contract.contract')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'event_type', 'created_at'], name='contract_co_contrac_b94d57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='contractversion',
            index=models.Index(fields=['contract', 'version_number'], name='contract_co_contrac_43e395_idx'),
        ),
        migrations.AddIndex(
            model_name='contractversion',
            index=models.Index(fields=['contract', 'is_frozen'], name='contract_co_contrac_e9baac_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractversion',
            unique_together={('contract', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='contractsignature',
            index=models.Index(fields=['contract_version', 'signer_role'], name='contract_co_contrac_b890b4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contractsignature',
            unique_together={('contract_version', 'signer_role')},
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['contract_version', 'kind'], name='contract_co_contrac_80cca2_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdocument',
            index=models.Index(fields=['sha256'], name='contract_co_sha256_5610b4_idx'),
        ),
        migrations.AddIndex(
            model_name='platformattestation',
            index=models.Index(fields=['verification_code'], name='contract_pl_verific_056468_idx'),
        ),
    ]
