# Generated by Django 5.2.15 on 2026-06-16 06:57

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0006_contract_finalized_at_contract_finalized_by_and_more'),
        ('servicerequest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Proposed price in IQD', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Amount')),
                ('currency', models.CharField(default='IQD', editable=False, max_length=3, verbose_name='Currency')),
                ('description', models.TextField(help_text='Detailed scope of work', verbose_name='Description')),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Estimated Duration (Days)')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='DRAFT', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='servicerequest.servicerequest', verbose_name='Service Request')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_request', 'status'], name='contract_of_service_edf800_idx'), models.Index(fields=['status'], name='contract_of_status_3073fc_idx')],
            },
        ),
    ]
