# Generated by Django 5.2.15 on 2026-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_offer'),
        ('servicerequest', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACCEPTED')), fields=('service_request',), name='uq_offer_accepted_per_request'),
        ),
    ]
