# Generated by Django 5.2.15 on 2026-06-20 07:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_offer_uq_offer_accepted_per_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='When contract execution was activated', null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When contract was completed (escrow still held)', null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_acceptance', 'Pending Acceptance'), ('pending_signatures', 'Pending Signatures'), ('pending_finalization', 'Pending Finalization'), ('in_progress', 'In Progress'), ('active', 'Active'), ('completion_requested', 'Completion Requested'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='draft', help_text='Current contract status', max_length=50),
        ),
        migrations.CreateModel(
            name='ExecutionMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text='Order of milestone within contract')),
                ('title', models.CharField(help_text='Milestone title', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of work')),
                ('due_date', models.DateField(blank=True, help_text='Target completion date', null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision Requested'), ('APPROVED', 'Approved'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current milestone status', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, help_text='When technician started work', null=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When technician submitted deliverable', null=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='When client approved', null=True)),
                ('revision_count', models.PositiveIntegerField(default=0, help_text='Number of revision cycles')),
                ('contract', models.ForeignKey(help_text='Parent contract', on_delete=django.db.models.deletion.CASCADE, related_name='execution_milestones', to='contract.contract')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the milestone', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execution Milestone',
                'verbose_name_plural': 'Execution Milestones',
                'ordering': ['contract', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DeliverableSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Submission version number (increments on resubmit)')),
                ('summary', models.TextField(help_text='Brief summary of completed work')),
                ('notes', models.TextField(blank=True, default='', help_text='Additional work notes')),
                ('external_link', models.URLField(blank=True, default='', help_text='External reference link (e.g., hosted doc)')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When submission was made')),
                ('submitted_by', models.ForeignKey(help_text='Technician who submitted', on_delete=django.db.models.deletion.CASCADE, related_name='deliverable_submissions', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(help_text='Milestone being submitted', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contract.executionmilestone')),
            ],
            options={
                'verbose_name': 'Deliverable Submission',
                'verbose_name_plural': 'Deliverable Submissions',
                'ordering': ['milestone', '-version'],
            },
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(help_text='Reason for revision request')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('RESOLVED', 'Resolved')], db_index=True, default='OPEN', help_text='Revision status', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When revision was resolved', null=True)),
                ('revision_number', models.PositiveIntegerField(default=1, help_text='Sequential revision number for this milestone')),
                ('milestone', models.ForeignKey(help_text='Milestone being revised', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contract.executionmilestone')),
                ('requested_by', models.ForeignKey(help_text='Client who requested revision', on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(help_text='Submission being revised', on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='contract.deliverablesubmission')),
            ],
            options={
                'verbose_name': 'Revision Request',
                'verbose_name_plural': 'Revision Requests',
                'ordering': ['milestone', '-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='CompletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completion_message', models.TextField(blank=True, default='', help_text='Final summary from technician')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', help_text='Completion request status', max_length=20)),
                ('response_message', models.TextField(blank=True, default='', help_text='Client response or rejection reason')),
                ('responded_at', models.DateTimeField(blank=True, help_text='When client responded', null=True)),
                ('contract', models.ForeignKey(help_text='Contract to complete', on_delete=django.db.models.deletion.CASCADE, related_name='completion_requests', to='contract.contract')),
                ('requested_by', models.ForeignKey(help_text='Technician requesting completion', on_delete=django.db.models.deletion.CASCADE, related_name='completion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Completion Request',
                'verbose_name_plural': 'Completion Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['contract', 'status'], name='contract_co_contrac_fb1247_idx'), models.Index(fields=['status'], name='contract_co_status_103738_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='executionmilestone',
            index=models.Index(fields=['contract', 'sequence'], name='contract_ex_contrac_89699e_idx'),
        ),
        migrations.AddIndex(
            model_name='executionmilestone',
            index=models.Index(fields=['contract', 'status'], name='contract_ex_contrac_70b1f7_idx'),
        ),
        migrations.AddIndex(
            model_name='executionmilestone',
            index=models.Index(fields=['status'], name='contract_ex_status_906755_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='executionmilestone',
            unique_together={('contract', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='deliverablesubmission',
            index=models.Index(fields=['milestone', 'version'], name='contract_de_milesto_2b8733_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverablesubmission',
            index=models.Index(fields=['submitted_by'], name='contract_de_submitt_ca046f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='deliverablesubmission',
            unique_together={('milestone', 'version')},
        ),
        migrations.AddIndex(
            model_name='revisionrequest',
            index=models.Index(fields=['milestone', 'status'], name='contract_re_milesto_200b57_idx'),
        ),
        migrations.AddIndex(
            model_name='revisionrequest',
            index=models.Index(fields=['submission'], name='contract_re_submiss_4a7c68_idx'),
        ),
    ]
