# Generated by Django 5.2.15 on 2026-06-15 15:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image_and_more'),
        ('category', '0002_category_is_delete_skill_is_delete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Brief title for the service request', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='Detailed description of the service needed', verbose_name='Description')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Governorate')),
                ('service_address', models.CharField(blank=True, max_length=500, null=True, verbose_name='Service Address')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Preferred Date')),
                ('preferred_time', models.TimeField(blank=True, null=True, verbose_name='Preferred Time')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Urgent')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='category.category', verbose_name='Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.clientprofile', verbose_name='Client')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='category.skill', verbose_name='Skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='accounts.technicianprofile', verbose_name='Technician')),
            ],
            options={
                'verbose_name': 'Service Request',
                'verbose_name_plural': 'Service Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client', 'status'], name='servicerequ_client__2cbdb8_idx'), models.Index(fields=['technician', 'status'], name='servicerequ_technic_4d5e43_idx'), models.Index(fields=['status'], name='servicerequ_status_af9069_idx')],
            },
        ),
    ]
