# Generated by Django 5.2.15 on 2026-06-11 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verb', models.CharField(db_index=True, max_length=50)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_repr', models.CharField(blank=True, max_length=255)),
                ('audience', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], db_index=True, default='system', max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activity logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='notificatio_actor_i_7d09eb_idx'), models.Index(fields=['target_type', 'target_id'], name='notificatio_target__eb1e6e_idx'), models.Index(fields=['audience', 'created_at'], name='notificatio_audienc_92ece9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('contract_created', 'Contract Created'), ('contract_proposal_submitted', 'Proposal Submitted'), ('contract_accepted', 'Contract Accepted'), ('contract_canceled', 'Contract Canceled'), ('contract_completed', 'Contract Completed'), ('stage_submitted', 'Stage Submitted'), ('stage_approved', 'Stage Approved'), ('extension_requested', 'Extension Requested'), ('extension_approved', 'Extension Approved'), ('extension_rejected', 'Extension Rejected'), ('review_created', 'Review Created'), ('review_responded', 'Review Responded'), ('review_reported', 'Review Reported'), ('review_moderated', 'Review Moderated'), ('wallet_transaction', 'Wallet Transaction'), ('payment_intent_created', 'Payment Intent Created'), ('payment_intent_paid', 'Payment Intent Paid'), ('withdrawal_requested', 'Withdrawal Requested'), ('withdrawal_approved', 'Withdrawal Approved'), ('withdrawal_rejected', 'Withdrawal Rejected'), ('technician_approved', 'Technician Approved'), ('technician_rejected', 'Technician Rejected'), ('system', 'System')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_dd6756_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_18c9bd_idx'), models.Index(fields=['target_type', 'target_id'], name='notificatio_target__6d7a6a_idx')],
            },
        ),
    ]
