# Generated by Django 5.2.15 on 2026-06-27 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_idx_notif_cleanup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offers', models.BooleanField(default=True)),
                ('contracts', models.BooleanField(default=True)),
                ('payments', models.BooleanField(default=True)),
                ('execution', models.BooleanField(default=True)),
                ('messages', models.BooleanField(default=True)),
                ('disputes', models.BooleanField(default=True)),
                ('refunds', models.BooleanField(default=True)),
                ('reviews', models.BooleanField(default=True)),
                ('security', models.BooleanField(default=True)),
                ('system', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False, help_text='Reserved; production email delivery is deferred.')),
                ('push_enabled', models.BooleanField(default=False, help_text='Reserved; production push delivery is deferred.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification preference',
                'verbose_name_plural': 'Notification preferences',
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='body_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='notification',
            name='deduplication_key',
            field=models.CharField(blank=True, max_length=160, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_key',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['deduplication_key'], name='notificatio_dedupli_d6307b_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
