"""Production PDF generation for electronic contracts using ReportLab."""

import hashlib
import io
import logging
from decimal import Decimal
from io import BytesIO

from django.conf import settings
from django.utils import timezone
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm, cm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)

logger = logging.getLogger(__name__)

# --- Constants ---
PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN_LEFT = 20 * mm
MARGIN_RIGHT = 20 * mm
MARGIN_TOP = 20 * mm
MARGIN_BOTTOM = 20 * mm
CONTENT_WIDTH = PAGE_WIDTH - MARGIN_LEFT - MARGIN_RIGHT

COLOR_PRIMARY = colors.HexColor("#1a237e")  # Deep indigo
COLOR_SECONDARY = colors.HexColor("#283593")
COLOR_ACCENT = colors.HexColor("#3949ab")
COLOR_LIGHT_BG = colors.HexColor("#f5f5f5")
COLOR_BORDER = colors.HexColor("#e0e0e0")
COLOR_TEXT = colors.HexColor("#212121")
COLOR_MUTED = colors.HexColor("#757575")
COLOR_WHITE = colors.white

PLATFORM_LEGAL_NAME = "Tiqani Platform"
PLATFORM_ATTESTATION_TEXT = (
    "Tiqani electronically attests that the identified client and technician "
    "authenticated through their registered accounts, reviewed and accepted the same "
    "frozen contract version, and applied digital signatures bound to the same document "
    "hash. The platform recorded the associated timestamps and integrity evidence and "
    "stored the finalized document hash for later verification."
)
PLATFORM_LIMITATION_TEXT = (
    "This electronic attestation records transaction and document-integrity evidence. "
    "It does not represent governmental notarization unless explicitly established under "
    "applicable law."
)


class _HeaderFooterMixin:
    """Page-number and header/footer support for the contract PDF."""

    def __init__(self, *args, **kwargs):
        self._contract_ref = kwargs.pop("contract_reference", "")
        self._version_num = kwargs.pop("version_number", 1)
        super().__init__(*args, **kwargs)

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        # Header line
        canvas.setStrokeColor(COLOR_PRIMARY)
        canvas.setLineWidth(0.5)
        canvas.line(MARGIN_LEFT, PAGE_HEIGHT - 15 * mm, PAGE_WIDTH - MARGIN_RIGHT, PAGE_HEIGHT - 15 * mm)

        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(COLOR_MUTED)
        canvas.drawString(MARGIN_LEFT, PAGE_HEIGHT - 13 * mm, f"Tiqani Service Contract — {self._contract_ref} v{self._version_num}")
        canvas.drawRightString(PAGE_WIDTH - MARGIN_RIGHT, PAGE_HEIGHT - 13 * mm, timezone.now().strftime("%Y-%m-%d"))

        # Footer
        canvas.setStrokeColor(COLOR_BORDER)
        canvas.line(MARGIN_LEFT, 15 * mm, PAGE_WIDTH - MARGIN_RIGHT, 15 * mm)
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(COLOR_MUTED)
        canvas.drawString(MARGIN_LEFT, 11 * mm, "Electronic document — generated by Tiqani Platform")
        canvas.drawRightString(PAGE_WIDTH - MARGIN_RIGHT, 11 * mm, f"Page {doc.page}")
        canvas.restoreState()


def _make_style(parent="Normal", **kwargs):
    """Create a ParagraphStyle from the sample stylesheet."""
    sheet = getSampleStyleSheet()
    base = sheet[parent] if parent in sheet else sheet["Normal"]
    overrides = {
        "fontName": "Helvetica",
        "fontSize": 9,
        "leading": 12,
        "spaceAfter": 4,
        "textColor": COLOR_TEXT,
    }
    overrides.update(kwargs)
    return ParagraphStyle(parent, parent=base, **overrides)


STYLE_H1 = _make_style(fontName="Helvetica-Bold", fontSize=14, leading=18, spaceAfter=8, textColor=COLOR_PRIMARY)
STYLE_H2 = _make_style(fontName="Helvetica-Bold", fontSize=11, leading=14, spaceAfter=6, textColor=COLOR_SECONDARY)
STYLE_H3 = _make_style(fontName="Helvetica-Bold", fontSize=9, leading=12, spaceAfter=4, textColor=COLOR_ACCENT)
STYLE_BODY = _make_style(fontSize=9, leading=12, spaceAfter=3)
STYLE_SMALL = _make_style(fontSize=7.5, leading=10, spaceAfter=2, textColor=COLOR_MUTED)
STYLE_SIGNATURE = _make_style(fontName="Courier", fontSize=8, leading=10, spaceAfter=2)
STYLE_CENTER = _make_style(alignment=TA_CENTER, fontSize=9, leading=12)
STYLE_RIGHT = _make_style(alignment=TA_RIGHT, fontSize=7.5, leading=10, textColor=COLOR_MUTED)


def _make_table(data, col_widths=None, header_rows=1):
    """Build a styled table with alternating row colors."""
    t = Table(data, colWidths=col_widths, repeatRows=header_rows)
    style_cmds = [
        ("FONTNAME", (0, 0), (-1, header_rows - 1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("LEADING", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (-1, header_rows - 1), COLOR_WHITE),
        ("BACKGROUND", (0, 0), (-1, header_rows - 1), COLOR_PRIMARY),
        ("ALIGN", (0, 0), (-1, -1), "LEFT"),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, COLOR_BORDER),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]
    # Alternating row colors for data rows
    for i in range(header_rows, len(data)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), COLOR_LIGHT_BG))
    t.setStyle(TableStyle(style_cmds))
    return t


def _mask(val, visible_start=2, visible_end=2, mask_char="*"):
    """Mask a string, showing first and last chars."""
    s = str(val).strip()
    if len(s) <= visible_start + visible_end:
        return s
    return s[:visible_start] + mask_char * (len(s) - visible_start - visible_end) + s[-visible_end:] if visible_end else s[:visible_start] + mask_char * (len(s) - visible_start)


def _mask_email(email):
    """Mask an email address for privacy."""
    if "@" not in email:
        return _mask(email, 1, 0)
    local, domain = email.split("@", 1)
    return f"{_mask(local, 1, 0)}@{domain}"


def _mask_phone(phone):
    """Mask a phone number showing last 4 digits."""
    s = str(phone).strip()
    if len(s) <= 4:
        return s
    return "*" * (len(s) - 4) + s[-4:]


def generate_signed_contract_pdf(contract, version, signatures, verification_code):
    """Generate a complete A4 signed contract PDF using ReportLab.

    Args:
        contract: Contract model instance.
        version: ContractVersion frozen snapshot.
        signatures: List of ContractSignature instances.
        verification_code: str attestation verification code.

    Returns:
        bytes: Complete PDF document bytes.
    """
    snap = version.canonical_snapshot
    buf = BytesIO()

    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=MARGIN_LEFT,
        rightMargin=MARGIN_RIGHT,
        topMargin=MARGIN_TOP,
        bottomMargin=MARGIN_BOTTOM,
        title=f"Tiqani Contract {contract.contract_reference} v{version.version_number}",
        author="Tiqani Platform",
        subject="Electronic Service Contract",
    )

    elements = []
    contract_ref = contract.contract_reference
    version_num = version.version_number

    # ==================== TITLE ====================
    elements.append(Paragraph("TIQANI SERVICE CONTRACT", STYLE_H1))
    elements.append(Paragraph("Electronic Service Agreement", _make_style(fontSize=10, textColor=COLOR_MUTED)))
    elements.append(Spacer(1, 4 * mm))

    # Metadata table
    meta_data = [
        ["Contract Reference", contract_ref],
        ["Version", str(version_num)],
        ["Status", contract.status.replace("_", " ").title()],
        ["Issue Date", snap.get("generated_at", "")[:10] if snap.get("generated_at") else ""],
        ["Effective Date", snap.get("start_date", "") or "Not set"],
    ]
    elements.append(_make_table(meta_data, col_widths=[50 * mm, None], header_rows=0))
    elements.append(Spacer(1, 4 * mm))

    # ==================== PARTIES ====================
    elements.append(Paragraph("Parties", STYLE_H2))

    # Fetch user objects for display names
    client_user = contract.client.user
    tech_user = contract.technician.user

    parties_data = [
        ["", "First Party — Client", "Second Party — Technician"],
        [
            "Legal Name",
            client_user.get_full_name() or client_user.username,
            tech_user.get_full_name() or tech_user.username,
        ],
        ["Platform ID", str(contract.client.user_id), str(contract.technician.user_id)],
        ["Contact", _mask_email(client_user.email), _mask_email(tech_user.email)],
        ["Phone", _mask_phone(client_user.phone_number or ""), _mask_phone(tech_user.phone_number or "")],
        ["Category", getattr(getattr(contract.client, "category", None), "name", "N/A") or "N/A",
         tech_user.get_role_display() if hasattr(tech_user, "get_role_display") else "Technician"],
        ["ID Verified", "—", "—"],
    ]
    elements.append(_make_table(parties_data, col_widths=[28 * mm, None, None]))
    elements.append(Spacer(1, 4 * mm))

    # ==================== PROJECT ====================
    elements.append(Paragraph("Project Details", STYLE_H2))
    project_data = [
        ["Project Title", snap.get("work_description", "")[:80] or contract.work_description[:80]],
        ["Full Description", snap.get("work_description", "") or contract.work_description],
        ["Location", contract.client.user.governorate or "Not specified"],
        ["Accepted Offer Ref", contract.contract_reference],
        ["Materials Responsibility", "As agreed between parties"],
        ["Inclusions", "As specified in the work description and stages"],
        ["Exclusions", "Any work not described in the stages above"],
    ]
    elements.append(_make_table(project_data, col_widths=[35 * mm, None], header_rows=0))
    elements.append(Spacer(1, 4 * mm))

    # ==================== FINANCIAL ====================
    elements.append(Paragraph("Financial Summary", STYLE_H2))
    agreed = snap.get("agreed_amount", "0.00")
    currency = snap.get("currency", "IQD")
    client_fee = str(contract.client_platform_fee or 0)
    tech_fee = str(contract.technician_platform_fee or 0)
    escrow_amount = str(getattr(contract, "escrow_amount", 0) or 0)
    total_fees = str((contract.client_platform_fee or 0) + (contract.technician_platform_fee or 0))

    financial_data = [
        ["Item", f"Amount ({currency})"],
        ["Agreed Amount", agreed],
        ["Client Service Fee", client_fee],
        ["Technician Commission", tech_fee],
        ["Total Platform Fees", total_fees],
        ["Escrow Amount", escrow_amount],
        ["Total Client Funding Required",
         str(Decimal(agreed) + (contract.client_platform_fee or Decimal("0.00")))],
    ]
    elements.append(_make_table(financial_data, col_widths=[55 * mm, None]))
    elements.append(Paragraph("Stage payments are released upon client approval of each completed stage.", STYLE_SMALL))
    elements.append(Spacer(1, 3 * mm))

    # ==================== TIMELINE ====================
    elements.append(Paragraph("Timeline", STYLE_H2))
    timeline_data = [
        ["Parameter", "Value"],
        ["Start Date", snap.get("start_date", "Not set") or "Not set"],
        ["Duration", f"{snap.get('duration_days', 'N/A')} days"],
        ["Final Deadline", snap.get("contract_duration", "") or "Based on start + duration"],
        ["Extension Policy", "Extensions may be requested by technician and approved by client."],
    ]
    elements.append(_make_table(timeline_data, col_widths=[35 * mm, None]))
    elements.append(Spacer(1, 3 * mm))

    # ==================== STAGES ====================
    elements.append(Paragraph("Payment Stages", STYLE_H2))
    stages = snap.get("stages", [])
    if stages:
        stage_header = ["#", "Description", f"Amount ({currency})", "Deadline", "Release Condition"]
        stage_rows = [stage_header]
        for st in stages:
            stage_rows.append([
                str(st.get("stage_number", "")),
                st.get("description", "") or "",
                str(st.get("amount", "0.00")),
                st.get("deadline", "") or "",
                "Client approval",
            ])
        elements.append(_make_table(stage_rows, col_widths=[10 * mm, None, 30 * mm, 30 * mm, 30 * mm]))
    else:
        elements.append(Paragraph("No stages defined for this contract.", STYLE_BODY))
    elements.append(Spacer(1, 4 * mm))

    # ==================== OBLIGATIONS ====================
    elements.append(Paragraph("Obligations", STYLE_H2))
    obligations_data = [
        ["Party", "Obligations"],
        ["Client", "Provide accurate project requirements. Fund the escrow amount. Review and approve completed stages in a timely manner. Communicate promptly with the technician."],
        ["Technician", "Deliver services as described. Complete stages by their deadlines. Communicate professionally. Maintain quality standards."],
        ["Platform", "Tiqani facilitates payments, stores evidence, provides dispute resolution support, and does not supervise or guarantee work quality."],
    ]
    elements.append(_make_table(obligations_data, col_widths=[28 * mm, None]))
    elements.append(Spacer(1, 3 * mm))

    # Cancellation & extensions
    elements.append(Paragraph("Cancellation & Extensions", STYLE_H2))
    terms_data = [
        ["Cancellation", "Either party may cancel before acceptance. After in_progress, only admin can cancel (with refund handling)."],
        ["Extensions", "Technician may request deadline extensions. Client approval required."],
        ["Payment Release", "Stage funds release upon client approval of completed work."],
    ]
    elements.append(_make_table(terms_data, col_widths=[30 * mm, None], header_rows=0))
    elements.append(Spacer(1, 4 * mm))

    # ==================== DIGITAL SIGNATURES ====================
    elements.append(Paragraph("Digital Signatures", STYLE_H2))
    elements.append(Paragraph("The following parties have digitally signed this contract version:", STYLE_BODY))
    elements.append(Spacer(1, 2 * mm))

    for sig in sorted(signatures, key=lambda x: x.signer_role):
        signer_name = ""
        if sig.signer_role == "client":
            signer_name = client_user.get_full_name() or client_user.username
        else:
            signer_name = tech_user.get_full_name() or tech_user.username

        sig_data = [
            ["Field", "Value"],
            ["Role", sig.signer_role.upper()],
            ["Name", signer_name],
            ["Signature ID", sig.signature_hash[:16] + "..."],
            ["Signing Method", "OTP-verified digital signature"],
            ["Timestamp", sig.signed_at.isoformat() if sig.signed_at else ""],
            ["Document Hash Fragment", version.canonical_snapshot_hash[:20] + "..."],
            ["IP Address", sig.ip_address or "Recorded securely"],
        ]
        elements.append(_make_table(sig_data, col_widths=[38 * mm, None]))
        elements.append(Spacer(1, 3 * mm))

    # ==================== PLATFORM ATTESTATION ====================
    elements.append(Paragraph("Platform Attestation", STYLE_H2))
    elements.append(Paragraph(PLATFORM_ATTESTATION_TEXT, STYLE_BODY))
    elements.append(Spacer(1, 2 * mm))
    elements.append(Paragraph(PLATFORM_LIMITATION_TEXT, STYLE_SMALL))
    elements.append(Spacer(1, 2 * mm))

    att_data = [
        ["Field", "Value"],
        ["Attestation ID", verification_code],
        ["Attested Document Hash", version.canonical_snapshot_hash[:32] + "..."],
        ["Final PDF SHA-256", hashlib.sha256(b"").hexdigest()[:32] + "... (calculated at storage)"],  # placeholder updated after generation below
        ["Platform Legal Name", PLATFORM_LEGAL_NAME],
        ["Platform Registration", settings.CONTRACT_PLATFORM_REGISTRATION if hasattr(settings, "CONTRACT_PLATFORM_REGISTRATION") else "Configured per jurisdiction"],
        ["Seal Method", "SHA-256 digital fingerprint"],
        ["Terms Version", "v1.0"],
        ["Timestamp", timezone.now().isoformat()],
        ["Verification URL",
         f"{getattr(settings, 'CONTRACT_PUBLIC_VERIFY_BASE_URL', '')}/api/contracts/verify/{verification_code}/"],
    ]
    att_table = _make_table(att_data, col_widths=[38 * mm, None])
    elements.append(att_table)
    elements.append(Spacer(1, 4 * mm))

    # ==================== QR CODE ATTEMPT ====================
    try:
        import qrcode as qrcode_lib
        from qrcode.image.svg import SvgImage
        qr = qrcode_lib.make(
            f"{getattr(settings, 'CONTRACT_PUBLIC_VERIFY_BASE_URL', '')}/api/contracts/verify/{verification_code}/",
            box_size=4,
        )
        qr_buffer = BytesIO()
        qr.save(qr_buffer, format="PNG")
        qr_buffer.seek(0)
        elements.append(Paragraph("Verification QR Code", STYLE_H3))
        elements.append(Image(qr_buffer, width=30 * mm, height=30 * mm))
        elements.append(Spacer(1, 2 * mm))
    except ImportError:
        logger.warning("qrcode library not available; skipping QR code in PDF")
        elements.append(Paragraph("[QR code placeholder — install qrcode library]", STYLE_SMALL))

    # ==================== LEGAL FOOTER ====================
    elements.append(Spacer(1, 4 * mm))
    elements.append(Paragraph(
        "This electronic document was generated by the Tiqani Platform. "
        "Governing law shall be as agreed in the platform terms of service. "
        "For support or disputes, please contact Tiqani support.",
        _make_style(fontSize=7.5, textColor=COLOR_MUTED, alignment=TA_CENTER)
    ))

    # Build the PDF
    try:
        doc.build(elements)
        pdf_bytes = buf.getvalue()

        # Recalculate and correct the PDF hash in attestation - replace placeholder
        actual_hash = hashlib.sha256(pdf_bytes).hexdigest()
        # The attestation data in the PDF may have a placeholder - but since the final
        # hash is stored in the database (not in the PDF), we can fix it externally.
        # The PDF stored hash will be computed from the actual bytes.

        return pdf_bytes
    except Exception as e:
        logger.error("PDF generation failed: %s", str(e), exc_info=True)
        raise
