# Generated by Django 6.0 on 2025-12-28 15:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='subskill',
            options={'ordering': ['skill', 'order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed category description', null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon class or name (e.g., fas fa-wrench)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Category is available for selection'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured on home page'),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in listings'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed skill description', null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Skill is available for selection'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within category'),
        ),
        migrations.AddField(
            model_name='skill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='subskill',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='subskill',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed sub-skill description', null=True),
        ),
        migrations.AddField(
            model_name='subskill',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Difficulty level of this sub-skill', max_length=20),
        ),
        migrations.AddField(
            model_name='subskill',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Sub-skill is available for selection'),
        ),
        migrations.AddField(
            model_name='subskill',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order within skill'),
        ),
        migrations.AddField(
            model_name='subskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, help_text='Category name (e.g., HVAC, Plumbing)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='category.category'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(help_text='Skill name (e.g., Installation, Repair)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='name',
            field=models.CharField(help_text='Sub-skill name (e.g., AC Installation, Heat Pump Installation)', max_length=255),
        ),
        migrations.AlterField(
            model_name='subskill',
            name='skill',
            field=models.ForeignKey(help_text='Parent skill', on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='category.skill'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='category_ca_is_acti_6c3710_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='category_ca_is_feat_9f734f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_ca_parent__ed1cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='category_ca_order_a92de7_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active'], name='category_sk_is_acti_c2c903_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['order'], name='category_sk_order_5cf9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['is_active'], name='category_su_is_acti_cf08e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['difficulty_level'], name='category_su_difficu_42ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['order'], name='category_su_order_7ba6d6_idx'),
        ),
    ]
