# Generated by Django 5.2.15 on 2026-06-12 17:58

import chat.models
import django.core.validators
import django.db.models.deletion
import tiqani_v3.file_validators
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image_and_more'),
        ('contract', '0005_alter_contractstage_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('TEXT', 'Text'), ('FILE', 'File'), ('SYSTEM', 'System'), ('PRICE_OFFER', 'Price Offer'), ('PRICE_ACCEPTED', 'Price Accepted'), ('CONTRACT_LINKED', 'Contract Linked')], db_index=True, default='TEXT', max_length=20, verbose_name='Message Type')),
                ('body', models.TextField(blank=True, default='', max_length=2000, verbose_name='Message Body')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=chat.models.chat_attachment_path, validators=[tiqani_v3.file_validators.validate_document_file], verbose_name='Attachment')),
                ('attachment_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Attachment Name')),
                ('attachment_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Attachment Size (bytes)')),
                ('attachment_content_type', models.CharField(blank=True, default='', max_length=100, verbose_name='Attachment Content Type')),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price Amount')),
                ('price_currency', models.CharField(default='IQD', max_length=3, verbose_name='Price Currency')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Edited At')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Service Chat Message',
                'verbose_name_plural': 'Service Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceChatRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROPOSAL_CREATED', 'Proposal Created'), ('CONTRACT_LINKED', 'Contract Linked'), ('CLOSED', 'Closed'), ('BLOCKED', 'Blocked')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Last Message At')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed At')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_client', to='accounts.clientprofile', verbose_name='Client')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms_closed', to=settings.AUTH_USER_MODEL, verbose_name='Closed By')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('linked_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='contract.contract', verbose_name='Linked Contract')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms_as_technician', to='accounts.technicianprofile', verbose_name='Technician')),
            ],
            options={
                'verbose_name': 'Service Chat Room',
                'verbose_name_plural': 'Service Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='ServiceChatReadState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Read At')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Unread Count')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('last_read_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.servicechatmessage', verbose_name='Last Read Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='chat.servicechatroom', verbose_name='Room')),
            ],
            options={
                'verbose_name': 'Service Chat Read State',
                'verbose_name_plural': 'Service Chat Read States',
            },
        ),
        migrations.AddField(
            model_name='servicechatmessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.servicechatroom', verbose_name='Room'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['client', 'technician', 'status'], name='idx_room_client_tech_status'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['technician', 'status', 'updated_at'], name='idx_room_tech_status_time'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['client', 'status', 'updated_at'], name='idx_room_client_status_time'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['linked_contract'], name='idx_room_linked_contract'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['last_message_at'], name='idx_room_last_message'),
        ),
        migrations.AddIndex(
            model_name='servicechatreadstate',
            index=models.Index(fields=['user', 'updated_at'], name='idx_read_user_updated'),
        ),
        migrations.AddIndex(
            model_name='servicechatreadstate',
            index=models.Index(fields=['room', 'last_read_at'], name='idx_read_room_last_read'),
        ),
        migrations.AlterUniqueTogether(
            name='servicechatreadstate',
            unique_together={('room', 'user')},
        ),
        migrations.AddIndex(
            model_name='servicechatmessage',
            index=models.Index(fields=['room', 'created_at'], name='idx_msg_room_created'),
        ),
        migrations.AddIndex(
            model_name='servicechatmessage',
            index=models.Index(fields=['sender', 'created_at'], name='idx_msg_sender_created'),
        ),
        migrations.AddIndex(
            model_name='servicechatmessage',
            index=models.Index(fields=['room', 'message_type', 'created_at'], name='idx_msg_room_type_created'),
        ),
        migrations.AddIndex(
            model_name='servicechatmessage',
            index=models.Index(fields=['room', 'is_deleted', 'created_at'], name='idx_msg_room_deleted_created'),
        ),
    ]
