# Generated by Django 5.2.15 on 2026-06-15 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image_and_more'),
        ('chat', '0001_initial'),
        ('contract', '0006_contract_finalized_at_contract_finalized_by_and_more'),
        ('servicerequest', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechatroom',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='servicerequest.servicerequest', verbose_name='Service Request'),
        ),
        migrations.AddIndex(
            model_name='servicechatroom',
            index=models.Index(fields=['service_request'], name='idx_room_service_request'),
        ),
        migrations.AddConstraint(
            model_name='servicechatroom',
            constraint=models.UniqueConstraint(condition=models.Q(('service_request__isnull', False)), fields=('service_request',), name='uq_room_service_request'),
        ),
    ]
