# Generated by Django 5.2 on 2025-12-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contract.contract'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.wallet'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['governorate'], name='accounts_cu_governo_d4a715_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['user'], name='accounts_te_user_id_b9b9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_available', 'approved'], name='accounts_te_is_avai_b9e5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['rate', 'approved'], name='accounts_te_rate_e8f61c_idx'),
        ),
    ]
