# Generated by Django 6.0 on 2025-12-27 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('category', '0001_initial'),
        ('contract', '0001_initial'),
        ('ratereview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='technician_profile_reviews', to='ratereview.review'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='technicianimage',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.technicianprofile'),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='categories',
            field=models.ManyToManyField(related_name='technician_skill_sets', to='category.category'),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='skills',
            field=models.ManyToManyField(related_name='technician_skill_sets', to='category.skill'),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='sub_skills',
            field=models.ManyToManyField(related_name='technician_skill_sets', to='category.subskill'),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_sets', to='accounts.technicianprofile'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='contract.contract'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.wallet'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='accounts_cu_role_666d59_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['governorate'], name='accounts_cu_governo_d4a715_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['user'], name='accounts_ad_user_id_5cb986_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['user'], name='accounts_cl_user_id_7684f4_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['governorate'], name='accounts_cl_governo_9983cd_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['user'], name='accounts_de_user_id_b6b275_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['company_registration_number'], name='accounts_de_company_4632f6_idx'),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['user', 'created_at'], name='accounts_ot_user_id_5d938f_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['user'], name='accounts_te_user_id_b9b9b2_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['is_available', 'approved'], name='accounts_te_is_avai_b9e5b6_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['governorate'], name='accounts_te_governo_17bd8e_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['last_active'], name='accounts_te_last_ac_b57259_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianimage',
            index=models.Index(fields=['technician'], name='accounts_te_technic_fd287b_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianskillset',
            index=models.Index(fields=['technician'], name='accounts_te_technic_d46f96_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='accounts_wa_user_id_5a6305_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='accounts_wa_wallet__24e6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type'], name='accounts_wa_transac_565191_idx'),
        ),
    ]
