# Generated by Django 6.0 on 2026-01-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicianprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='Short professional title shown to clients (e.g., HVAC Specialist, Full-Stack Developer)', max_length=100, null=True),
        ),
    ]
