# Generated by Django 6.0 on 2025-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('ratereview', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='technicianprofile',
            name='accounts_te_governo_17bd8e_idx',
        ),
        migrations.RemoveIndex(
            model_name='technicianprofile',
            name='accounts_te_last_ac_b57259_idx',
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, help_text='Administrator approval status for technician to appear in public listings'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cached average rating (auto-calculated from reviews)', max_digits=3),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['approved'], name='accounts_te_approve_45f9fb_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianprofile',
            index=models.Index(fields=['rate', 'approved'], name='accounts_te_rate_e8f61c_idx'),
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='profile_image',
        ),
    ]
