# Generated by Django 5.2 on 2026-01-20 20:47

import accounts.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_technicianprofile_job_title'),
        ('category', '0002_category_is_delete_skill_is_delete_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'verbose_name': 'Admin Profile'},
        ),
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client Profile'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='otpverification',
            options={'verbose_name': 'OTP Code'},
        ),
        migrations.AlterModelOptions(
            name='technicianimage',
            options={'ordering': ['display_order', '-created_at'], 'verbose_name': 'Portfolio Image', 'verbose_name_plural': 'Portfolio Images'},
        ),
        migrations.AlterModelOptions(
            name='technicianprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Technician Profile'},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='technicianprofile',
            name='accounts_te_user_id_b9b9b2_idx',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='skill_sets',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='url1',
        ),
        migrations.RemoveField(
            model_name='technicianprofile',
            name='url2',
        ),
        migrations.AddField(
            model_name='technicianimage',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AddField(
            model_name='technicianimage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Cover Image'),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='github',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid GitHub profile URL.', regex='^(https?:\\/\\/)?(www\\.)?github\\.com\\/[A-Za-z0-9_-]+\\/?$')]),
        ),
        migrations.AddField(
            model_name='technicianprofile',
            name='linkedin',
            field=models.URLField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid LinkedIn profile URL.', regex='^(https?:\\/\\/)?(www\\.)?linkedin\\.com\\/in\\/[A-Za-z0-9_-]+\\/?$')]),
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Profile Complete'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('content_moderator', 'Moderator'), ('finance_admin', 'Finance')], default='system_admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Profile Complete'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='governorate',
            field=models.CharField(blank=True, choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى'), ('Halabja', 'حلبجة')], max_length=50, null=True, verbose_name='Governorate'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits starting with 075, 077, or 078.', regex='^07[5|7|8]\\d{8}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.universal_file_path, verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('technician', 'Technician'), ('admin', 'Admin')], default='client', max_length=20, verbose_name='User Role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='image',
            field=models.ImageField(upload_to=accounts.models.universal_file_path),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='accounts.technicianprofile'),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='approved',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Admin Approved'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='identification_documents',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.universal_file_path, verbose_name='ID Documents'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Available for Work'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_complete',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Profile Complete'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='e.g., HVAC Specialist, Full-Stack Developer', max_length=100, null=True, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='years_of_expertise',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='categories',
            field=models.ManyToManyField(blank=True, to='category.category'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='skills',
            field=models.ManyToManyField(blank=True, to='category.skill'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='sub_skills',
            field=models.ManyToManyField(blank=True, to='category.subskill'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='technician',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='accounts.technicianprofile'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='transaction_id',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
