# Generated by ChatGPT on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('escrow', 'Escrow'), ('release', 'Release'), ('platform_fee', 'Platform Fee')], db_index=True, max_length=20),
        ),
    ]
