# Generated by Django 6.0 on 2025-12-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dealershipprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='dealershipprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='dealershipprofile',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='dealershipprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='dealershipprofile',
            name='profile_image',
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['is_complete'], name='accounts_de_is_comp_2a6f72_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['is_delete'], name='accounts_de_is_dele_75a995_idx'),
        ),
    ]
