# Generated by Django 6.0 on 2025-12-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_dealershipprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about the admin user', null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('content_moderator', 'Content Moderator'), ('account_manager', 'Account Manager'), ('finance_admin', 'Financial Administrator')], default='system_admin', help_text='Specific administrative role and permissions', max_length=50),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['role'], name='accounts_ad_role_6e9707_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['is_complete'], name='accounts_ad_is_comp_0a1d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='adminprofile',
            index=models.Index(fields=['is_delete'], name='accounts_ad_is_dele_87ba0f_idx'),
        ),
    ]
