# Generated by ChatGPT on 2026-02-27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_wallettransaction_transaction_type'),
        ('contract', '0004_contract_client_platform_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='global_platform_wallet', editable=False, max_length=64, unique=True)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_fees_collected', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_client_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_technician_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Wallet',
                'verbose_name_plural': 'Platform Wallet',
            },
        ),
        migrations.CreateModel(
            name='PlatformWalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(db_index=True, default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('source_type', models.CharField(choices=[('client', 'Client'), ('technician', 'Technician'), ('system', 'System')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField()),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fee_transactions', to='contract.contract')),
                ('platform_wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounts.platformwallet')),
                ('source_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fee_transactions', to='accounts.customuser')),
                ('source_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fee_transactions', to='accounts.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
