# Generated by Django 6.0 on 2025-12-27 20:33

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_adminprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technicianimage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='technicianskillset',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='wallettransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='technicianimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technicianimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='technicianskillset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='is_used',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this OTP has been used'),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='otp_code',
            field=models.CharField(help_text='6-digit OTP code', max_length=6),
        ),
        migrations.AlterField(
            model_name='otpverification',
            name='verification_id',
            field=models.CharField(help_text='Unique verification identifier', max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Account balance in IQD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Transaction amount in IQD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='amount_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Equivalent USD amount at transaction time', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(help_text='Transaction description and details'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Exchange rate IQD to USD at transaction time', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('escrow', 'Escrow'), ('release', 'Release Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], db_index=True, help_text='Type of transaction', max_length=20),
        ),
        migrations.AddIndex(
            model_name='otpverification',
            index=models.Index(fields=['is_used'], name='accounts_ot_is_used_2d1107_idx'),
        ),
        migrations.AddIndex(
            model_name='technicianimage',
            index=models.Index(fields=['created_at'], name='accounts_te_created_157617_idx'),
        ),
    ]
