# Generated by Django 6.0 on 2026-02-27 08:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_platformwallet_and_platformwallettransaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Client Profile'},
        ),
        migrations.AlterField(
            model_name='platformwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='platformwallettransaction',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
