# Generated by Django 6.0 on 2025-12-28 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_technicianimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianprofile',
            name='skill_sets',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_profile_skill', to='accounts.technicianskillset'),
        ),
        migrations.AlterField(
            model_name='technicianskillset',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_set_records', to='accounts.technicianprofile'),
        ),
    ]
