# Generated by Django 6.0 on 2026-02-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_clientprofile_options_and_more'),
        ('contract', '0005_alter_contractstage_transaction'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='platformwallettransaction',
                    name='platform_wallet',
                ),
                migrations.RemoveField(
                    model_name='platformwallettransaction',
                    name='contract',
                ),
                migrations.RemoveField(
                    model_name='platformwallettransaction',
                    name='source_user',
                ),
                migrations.RemoveField(
                    model_name='platformwallettransaction',
                    name='source_wallet',
                ),
                migrations.RemoveField(
                    model_name='wallet',
                    name='user',
                ),
                migrations.RemoveField(
                    model_name='wallettransaction',
                    name='wallet',
                ),
                migrations.RemoveField(
                    model_name='wallettransaction',
                    name='contract',
                ),
                migrations.DeleteModel(
                    name='PlatformWallet',
                ),
                migrations.DeleteModel(
                    name='PlatformWalletTransaction',
                ),
                migrations.DeleteModel(
                    name='Wallet',
                ),
                migrations.DeleteModel(
                    name='WalletTransaction',
                ),
            ],
        ),
    ]
