# Generated by Django 5.2.15 on 2026-06-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_platformwallettransaction_platform_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('content_moderator', 'Moderator'), ('finance_admin', 'Finance'), ('account_manager', 'Account Manager')], default='system_admin', max_length=50),
        ),
    ]
