# Generated by Django 5.2.15 on 2026-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_adminprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('technician', 'Technician'), ('dealership', 'Dealership'), ('admin', 'Admin')], default='client', max_length=20, verbose_name='User Role'),
        ),
    ]
