# Generated by Django 5.2.15 on 2026-06-12 08:20

import accounts.models
import tiqani_v3.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.universal_file_path, validators=[tiqani_v3.file_validators.validate_profile_image_file], verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='technicianimage',
            name='image',
            field=models.ImageField(upload_to=accounts.models.universal_file_path, validators=[tiqani_v3.file_validators.validate_profile_image_file]),
        ),
        migrations.AlterField(
            model_name='technicianprofile',
            name='identification_documents',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.universal_file_path, validators=[tiqani_v3.file_validators.validate_document_file], verbose_name='ID Documents'),
        ),
    ]
