# Generated by Django 5.2 on 2025-12-30 20:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text='Category name (e.g., HVAC, Plumbing)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed category description', null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon class or name (e.g., fas fa-wrench)', max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Category is available for selection')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured on home page')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order in listings')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical structure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='category.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Skill name (e.g., Installation, Repair)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed skill description', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Skill is available for selection')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(help_text='Parent category', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='category.category')),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Sub-skill name (e.g., AC Installation, Heat Pump Installation)', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed sub-skill description', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Sub-skill is available for selection')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', help_text='Difficulty level of this sub-skill', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within skill')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(help_text='Parent skill', on_delete=django.db.models.deletion.CASCADE, related_name='sub_skills', to='category.skill')),
            ],
            options={
                'ordering': ['skill', 'order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='category_ca_name_654722_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='category_ca_is_acti_6c3710_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_featured'], name='category_ca_is_feat_9f734f_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='category_ca_parent__ed1cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['order'], name='category_ca_order_a92de7_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category'], name='category_sk_categor_8f5d99_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_active'], name='category_sk_is_acti_c2c903_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['order'], name='category_sk_order_5cf9d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('category', 'name')},
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['skill'], name='category_su_skill_i_682c16_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['is_active'], name='category_su_is_acti_cf08e8_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['difficulty_level'], name='category_su_difficu_42ec29_idx'),
        ),
        migrations.AddIndex(
            model_name='subskill',
            index=models.Index(fields=['order'], name='category_su_order_7ba6d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subskill',
            unique_together={('skill', 'name')},
        ),
    ]
