# Generated by Django 5.2 on 2025-12-30 20:53

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('contract', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(help_text='Overall rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('work_quality_rating', models.PositiveSmallIntegerField(blank=True, help_text='Specific score for quality of work', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_rating', models.PositiveSmallIntegerField(blank=True, help_text='Specific score for communication and responsiveness', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_rating', models.PositiveSmallIntegerField(blank=True, help_text='Specific score for timeliness and punctuality', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.PositiveSmallIntegerField(blank=True, help_text='Specific score for professionalism and conduct', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, help_text='Short headline for the review', max_length=150)),
                ('comment', models.TextField(blank=True, help_text='Detailed feedback from the client')),
                ('technician_response', models.TextField(blank=True, help_text='Optional response from the technician')),
                ('is_public', models.BooleanField(default=True, help_text='If false, hides the review from public listings')),
                ('is_verified', models.BooleanField(default=False, help_text='True when linked to a contract or manually approved')),
                ('helpful_count', models.PositiveIntegerField(default=0, help_text='Number of times users marked this review helpful')),
                ('reported_count', models.PositiveIntegerField(default=0, help_text='Number of times the review was reported')),
                ('flagged_at', models.DateTimeField(blank=True, help_text='When the review was flagged for moderation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(blank=True, help_text='Optional link to a contract to verify the engagement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='contract.contract')),
                ('reviewer', models.ForeignKey(help_text='User who submitted the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(help_text='Technician being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.technicianprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['technician', 'created_at'], name='ratereview__technic_6346cd_idx'), models.Index(fields=['rating'], name='ratereview__rating_3deb9f_idx'), models.Index(fields=['is_public'], name='ratereview__is_publ_8c2609_idx'), models.Index(fields=['is_verified'], name='ratereview__is_veri_4501e8_idx'), models.Index(fields=['contract', 'technician'], name='ratereview__contrac_334c45_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('reviewer', 'contract'), name='unique_reviewer_contract_review')],
            },
        ),
    ]
