# Generated by Django 5.2.15 on 2026-06-27 01:21

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_profile_image_and_more'),
        ('contract', '0009_contract_activated_at_contract_completed_at_and_more'),
        ('ratereview', '0002_reviewhelpful_reviewreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewModerationAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('hide', 'Hide'), ('restore', 'Restore'), ('verify', 'Verify'), ('unverify', 'Unverify'), ('report_resolved', 'Report Resolved')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReputationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('client', 'Client'), ('technician', 'Technician')], db_index=True, max_length=20)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('rating_1_count', models.PositiveIntegerField(default=0)),
                ('rating_2_count', models.PositiveIntegerField(default=0)),
                ('rating_3_count', models.PositiveIntegerField(default=0)),
                ('rating_4_count', models.PositiveIntegerField(default=0)),
                ('rating_5_count', models.PositiveIntegerField(default=0)),
                ('completed_contract_count', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(choices=[('new', 'New'), ('established', 'Established'), ('highly_rated', 'Highly Rated')], default='new', max_length=20)),
                ('last_recalculated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='edit_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='last_edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, help_text='User being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer_role',
            field=models.CharField(blank=True, choices=[('client', 'Client'), ('technician', 'Technician')], db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('hidden', 'Hidden'), ('removed', 'Removed')], db_index=True, default='published', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='technician',
            field=models.ForeignKey(blank=True, help_text='Technician tied to the contract or being reviewed', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.technicianprofile'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['reviewee', 'status'], name='ratereview__reviewe_1e2cfd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['contract', 'reviewer', 'reviewee'], name='ratereview__contrac_c9ef28_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False), ('reviewee__isnull', False)), fields=('contract', 'reviewer', 'reviewee'), name='unique_contract_reviewer_reviewee'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('reviewer', models.F('reviewee')), _negated=True), name='review_reviewer_not_reviewee'),
        ),
        migrations.AddField(
            model_name='reviewmoderationaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_moderation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewmoderationaction',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to='ratereview.review'),
        ),
        migrations.AddField(
            model_name='userreputationsnapshot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reputation_snapshots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='reviewmoderationaction',
            index=models.Index(fields=['review', 'created_at'], name='ratereview__review__4d9306_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewmoderationaction',
            index=models.Index(fields=['actor', 'created_at'], name='ratereview__actor_i_cb32b2_idx'),
        ),
        migrations.AddIndex(
            model_name='userreputationsnapshot',
            index=models.Index(fields=['user', 'role'], name='ratereview__user_id_1db049_idx'),
        ),
        migrations.AddIndex(
            model_name='userreputationsnapshot',
            index=models.Index(fields=['label'], name='ratereview__label_8b1a2b_idx'),
        ),
        migrations.AddConstraint(
            model_name='userreputationsnapshot',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique_user_reputation_role'),
        ),
    ]
