# Generated by Django 5.2.15 on 2026-06-23 13:26

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contract', '0009_contract_activated_at_contract_completed_at_and_more'),
        ('wallet', '0004_contractsettlement_and_withdrawal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractDispute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('work_not_delivered', 'Work Not Delivered'), ('work_incomplete', 'Work Incomplete'), ('quality_not_as_agreed', 'Quality Not as Agreed'), ('misrepresentation', 'Misrepresentation'), ('unauthorized_completion', 'Unauthorized Completion'), ('client_non_cooperation', 'Client Non-Cooperation'), ('scope_change', 'Scope Change'), ('payment_or_settlement_error', 'Payment or Settlement Error'), ('fraud_suspected', 'Fraud Suspected'), ('duplicate_payment', 'Duplicate Payment'), ('chargeback_received', 'Chargeback Received'), ('other', 'Other')], db_index=True, max_length=40)),
                ('category', models.CharField(blank=True, choices=[('pre_settlement', 'Pre-Settlement'), ('post_settlement_recoverable', 'Post-Settlement Recoverable'), ('post_settlement_partially_recoverable', 'Post-Settlement Partially Recoverable'), ('post_settlement_non_recoverable', 'Post-Settlement Non-Recoverable'), ('chargeback_review', 'Chargeback Review')], db_index=True, max_length=40, null=True)),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_response', 'Awaiting Response'), ('under_review', 'Under Review'), ('mediation', 'Mediation'), ('resolution_proposed', 'Resolution Proposed'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=30)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('response_due_at', models.DateTimeField(blank=True, null=True)),
                ('review_started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('resolution_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contract.contract')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respondent_disputes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract Dispute',
                'verbose_name_plural': 'Contract Disputes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChargebackEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason_code', models.CharField(blank=True, default='', max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('evidence_deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('under_review', 'Under Review'), ('evidence_submitted', 'Evidence Submitted'), ('upheld', 'Upheld'), ('rejected', 'Rejected'), ('partially_upheld', 'Partially Upheld'), ('closed', 'Closed')], db_index=True, default='received', max_length=25)),
                ('outcome', models.CharField(blank=True, default='', max_length=40)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargeback_events', to='contract.contract')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_chargebacks', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chargeback_events', to='dispute.contractdispute')),
            ],
            options={
                'verbose_name': 'Chargeback Event',
                'verbose_name_plural': 'Chargeback Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='dispute.contractdispute')),
            ],
            options={
                'verbose_name': 'Dispute Audit Event',
                'verbose_name_plural': 'Dispute Audit Events',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('image', 'Image'), ('message_reference', 'Message Reference'), ('deliverable_reference', 'Deliverable Reference'), ('milestone_reference', 'Milestone Reference'), ('other', 'Other')], default='document', max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(blank=True, null=True, upload_to='dispute_evidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp', 'txt', 'json'])])),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('integrity_hash', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='dispute.contractdispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Evidence',
                'verbose_name_plural': 'Dispute Evidence',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(choices=[('full_client_refund', 'Full Client Refund'), ('partial_client_refund', 'Partial Client Refund'), ('full_technician_award', 'Full Technician Award'), ('partial_technician_award', 'Partial Technician Award'), ('split_resolution', 'Split Resolution'), ('no_financial_change', 'No Financial Change'), ('dispute_rejected', 'Dispute Rejected'), ('manual_recovery_required', 'Manual Recovery Required'), ('chargeback_upheld', 'Chargeback Upheld'), ('chargeback_rejected', 'Chargeback Rejected')], max_length=40)),
                ('client_refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('technician_retained_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('platform_fee_reversal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('escrow_released_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('wallet_reversal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('unrecoverable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('outstanding_liability_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('resolution_reason', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='dispute.contractdispute')),
                ('resolved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Resolution',
                'verbose_name_plural': 'Dispute Resolutions',
            },
        ),
        migrations.CreateModel(
            name='DisputeStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statement', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='dispute.contractdispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispute Statement',
                'verbose_name_plural': 'Dispute Statements',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('source_type', models.CharField(choices=[('escrow', 'Escrow'), ('technician_wallet_reversal', 'Technician Wallet Reversal'), ('platform_fee_reversal', 'Platform Fee Reversal'), ('split_sources', 'Split Sources'), ('manual_recovery', 'Manual Recovery'), ('sandbox_provider', 'Sandbox Provider')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('partially_completed', 'Partially Completed')], db_index=True, default='pending', max_length=25)),
                ('refund_method', models.CharField(blank=True, default='', max_length=50)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, default='', max_length=100)),
                ('failure_message', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds_received', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='contract.contract')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_refunds', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='dispute.contractdispute')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_records', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Refund Record',
                'verbose_name_plural': 'Refund Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFinancialLiability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partially_recovered', 'Partially Recovered'), ('fully_recovered', 'Fully Recovered'), ('written_off', 'Written Off')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='dispute.contractdispute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_liabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Financial Liability',
                'verbose_name_plural': 'User Financial Liabilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractdispute',
            index=models.Index(fields=['contract', 'status'], name='dispute_con_contrac_a6aa98_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdispute',
            index=models.Index(fields=['opened_by', 'status'], name='dispute_con_opened__473b3d_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdispute',
            index=models.Index(fields=['respondent', 'status'], name='dispute_con_respond_237716_idx'),
        ),
        migrations.AddIndex(
            model_name='contractdispute',
            index=models.Index(fields=['assigned_staff', 'status'], name='dispute_con_assigne_2ed6b4_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeauditevent',
            index=models.Index(fields=['dispute', 'event_type'], name='dispute_dis_dispute_3655f5_idx'),
        ),
    ]
