# Generated by Django 6.0 on 2026-02-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformWallet',
            fields=[
            ],
            options={
                'verbose_name': 'Platform Wallet',
                'verbose_name_plural': 'Platform Wallets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.platformwallet',),
        ),
        migrations.CreateModel(
            name='PlatformWalletTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Platform Wallet Transaction',
                'verbose_name_plural': 'Platform Wallet Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.platformwallettransaction',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.wallet',),
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.wallettransaction',),
        ),
    ]
