# Generated by Django 5.2.15 on 2026-06-11 04:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contractstage_transaction'),
        ('wallet', '0002_delete_platformwallet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFeeConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Label for this fee config', max_length=128)),
                ('technician_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage deducted from technician payout', max_digits=5)),
                ('client_service_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Percentage added to client total as service/protection fee', max_digits=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('effective_from', models.DateTimeField(blank=True, null=True)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Platform Fee Config',
                'verbose_name_plural': 'Platform Fee Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('purpose', models.CharField(choices=[('contract_funding', 'Contract Funding'), ('wallet_deposit', 'Wallet Deposit'), ('withdrawal', 'Withdrawal')], default='contract_funding', max_length=30)),
                ('provider', models.CharField(choices=[('manual', 'Manual / Internal')], default='manual', max_length=30)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requires_action', 'Requires Action'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='contract.contract')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Intent',
                'verbose_name_plural': 'Payment Intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('earning_type', models.CharField(choices=[('technician_commission', 'Technician Commission'), ('client_service_fee', 'Client Service Fee'), ('adjustment', 'Adjustment')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('earned', 'Earned'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_earnings', to='contract.contract')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_earnings', to='contract.contractstage')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Platform Earning',
                'verbose_name_plural': 'Platform Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractPaymentBreakdown',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technician_commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('client_service_fee_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('technician_commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_service_fee_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technician_net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_breakdown', to='contract.contract')),
                ('fee_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.platformfeeconfig')),
            ],
            options={
                'verbose_name': 'Contract Payment Breakdown',
                'verbose_name_plural': 'Contract Payment Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('requested_method', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Withdrawal Request',
                'verbose_name_plural': 'Withdrawal Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
