# Generated by Django 5.2.15 on 2026-06-21 18:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_contract_activated_at_contract_completed_at_and_more'),
        ('wallet', '0003_platformfeeconfig_paymentintent_platformearning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='failure_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='failure_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ContractSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('released_principal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technician_net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('technician_commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('client_service_fee_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_platform_fee', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_code', models.CharField(blank=True, max_length=100)),
                ('failure_message', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('client_fee_earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_client_fee', to='wallet.platformearning')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='contract.contract')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment_breakdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.contractpaymentbreakdown')),
                ('platform_commission_earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_commission', to='wallet.platformearning')),
                ('technician_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_releases', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Contract Settlement',
                'verbose_name_plural': 'Contract Settlements',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('contract',), name='unique_completed_settlement_per_contract')],
            },
        ),
    ]
