# Generated by Django 5.2.15 on 2026-07-05 05:14

import django.core.validators
import django.db.models.deletion
import tiqani_v3.file_validators
import uuid
import wallet.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_contractsettlement_and_withdrawal_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletRechargeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='IQD', max_length=3)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending_review', max_length=20)),
                ('receipt_file', models.FileField(upload_to=wallet.models.wallet_recharge_receipt_upload_path, validators=[tiqani_v3.file_validators.validate_wallet_recharge_receipt_file])),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('approved_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge_request', to='wallet.wallettransaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_recharge_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_recharge_requests', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recharge_requests', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Recharge Request',
                'verbose_name_plural': 'Wallet Recharge Requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', 'created_at'], name='wallet_wall_user_id_62fb06_idx'), models.Index(fields=['status', 'created_at'], name='wallet_wall_status_fc866c_idx'), models.Index(fields=['wallet', 'status'], name='wallet_wall_wallet__0746c9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending_review')), fields=('user',), name='unique_pending_wallet_recharge_per_user')],
            },
        ),
    ]
