# Generated by Django 6.0 on 2025-12-27 20:20

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='technicians/uploads/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False, help_text='Administrator approval status for technician to appear in public listings')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 077, 078, or 075.', regex='^07[5|7|8]\\d{8}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.technician_profile_image_path)),
                ('job_title', models.CharField(blank=True, help_text='Professional title or role', max_length=100, null=True)),
                ('identification_documents', models.FileField(blank=True, help_text='Upload identification documents as a ZIP file (required for profile completion)', null=True, upload_to=accounts.models.technician_identification_docs_path)),
                ('url1', models.URLField(blank=True, max_length=255, null=True)),
                ('url2', models.URLField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('governorate', models.CharField(choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('years_of_expertise', models.PositiveIntegerField(default=0, help_text='Number of years of professional experience')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Cached average rating', max_digits=3)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('transaction_id', models.CharField(editable=False, max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('escrow', 'Escrow'), ('release', 'Release Payment'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('client', 'Client'), ('technician', 'Technician'), ('admin', 'Admin'), ('dealership', 'Dealership')], default='client', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 077, 078, or 075.', regex='^07[5|7|8]\\d{8}$')])),
                ('governorate', models.CharField(blank=True, choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='user_profiles/')),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('system_admin', 'System Administrator'), ('content_moderator', 'Content Moderator'), ('account_manager', 'Account Manager'), ('finance_admin', 'Financial Administrator')], default='system_admin', max_length=50)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='admin_profiles/')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 077, 078, or 075.', regex='^07[5|7|8]\\d{8}$')])),
                ('governorate', models.CharField(blank=True, choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits and start with 077, 078, or 075.', regex='^07[5|7|8]\\d{8}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.client_profile_image_path)),
                ('governorate', models.CharField(blank=True, choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=6, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DealershipProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_registration_number', models.CharField(max_length=50, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='dealership_profiles/')),
                ('phone_number', models.CharField(db_index=True, max_length=15, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('governorate', models.CharField(choices=[('Baghdad', 'بغداد'), ('Basra', 'البصرة'), ('Nineveh', 'نينوى'), ('Erbil', 'أربيل'), ('Sulaymaniyah', 'السليمانية'), ('Kirkuk', 'كركوك'), ('Duhok', 'دهوك'), ('Najaf', 'النجف'), ('Karbala', 'كربلاء'), ('Anbar', 'الأنبار'), ('Babil', 'بابل'), ('Maysan', 'ميسان'), ('Wasit', 'واسط'), ('Dhi Qar', 'ذي قار'), ('Muthanna', 'المثنى'), ('Qadisiyyah', 'القادسية'), ('Salah al-Din', 'صلاح الدين'), ('Diyala', 'ديالى')], max_length=50)),
                ('about', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('verification_id', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
