# Generated by Django 6.0 on 2025-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_technicianprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='clientprofile',
            name='accounts_cl_governo_9983cd_idx',
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['is_complete'], name='accounts_cl_is_comp_863e60_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprofile',
            index=models.Index(fields=['is_delete'], name='accounts_cl_is_dele_0133b9_idx'),
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='clientprofile',
            name='profile_image',
        ),
    ]
