# Generated by Django 6.0 on 2025-12-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_technicianprofile_skill_sets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicianprofile',
            name='reviews',
        ),
    ]
