# Generated by Django 5.2.15 on 2026-06-12 07:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0003_platformfeeconfig_paymentintent_platformearning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealershipProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255, verbose_name='Business Name')),
                ('owner_name', models.CharField(max_length=255, verbose_name='Owner Name')),
                ('phone', models.CharField(max_length=50, verbose_name='Phone')),
                ('governorate', models.CharField(max_length=100, verbose_name='Governorate')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('active', 'Active'), ('suspended', 'Suspended'), ('blocked', 'Blocked')], db_index=True, default='pending_review', max_length=20, verbose_name='Status')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('financially_locked', models.BooleanField(default=False, verbose_name='Financially Locked')),
                ('suspended', models.BooleanField(default=False, verbose_name='Suspended')),
                ('blocked', models.BooleanField(default=False, verbose_name='Blocked')),
                ('usage_limit_percent', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Usage Limit (%)')),
                ('min_required_guarantee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Minimum Required Guarantee (IQD)')),
                ('max_allowed_guarantee', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maximum Allowed Guarantee (IQD)')),
                ('single_cashout_limit', models.DecimalField(decimal_places=2, default=Decimal('1000000.00'), max_digits=15, verbose_name='Single Cash-out Limit (IQD)')),
                ('daily_cashout_limit', models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), max_digits=15, verbose_name='Daily Cash-out Limit (IQD)')),
                ('monthly_cashout_limit', models.DecimalField(decimal_places=2, default=Decimal('50000000.00'), max_digits=15, verbose_name='Monthly Cash-out Limit (IQD)')),
                ('cashout_enabled', models.BooleanField(default=True, verbose_name='Cash-out Enabled')),
                ('recharge_enabled', models.BooleanField(default=True, verbose_name='Recharge Enabled')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_dealerships', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dealership Profile',
                'verbose_name_plural': 'Dealership Profiles',
            },
        ),
        migrations.CreateModel(
            name='DealershipGuarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Cash Amount (IQD)')),
                ('bank_check_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Bank Check Amount (IQD)')),
                ('legal_document_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Legal Document Amount (IQD)')),
                ('total_guarantee_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Guarantee Amount (IQD)')),
                ('document_file', models.FileField(blank=True, null=True, upload_to='dealership/guarantees/', verbose_name='Document File')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_guarantees', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='dealership.dealershipprofile')),
            ],
            options={
                'verbose_name': 'Dealership Guarantee',
                'verbose_name_plural': 'Dealership Guarantees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('guarantee_added', 'Guarantee Added'), ('client_recharge', 'Client Recharge'), ('recharge_reversal', 'Recharge Reversal'), ('client_cashout', 'Client Cashout'), ('cashout_reversal', 'Cashout Reversal'), ('settlement_paid_to_platform', 'Settlement Paid to Platform'), ('settlement_paid_by_platform', 'Settlement Paid by Platform'), ('manual_adjustment', 'Manual Adjustment')], db_index=True, max_length=40, verbose_name='Transaction Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount (IQD)')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Balance After (IQD)')),
                ('reference_type', models.CharField(blank=True, max_length=50, verbose_name='Reference Type')),
                ('reference_id', models.UUIDField(blank=True, null=True, verbose_name='Reference ID')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='dealership.dealershipprofile')),
            ],
            options={
                'verbose_name': 'Dealership Credit Ledger',
                'verbose_name_plural': 'Dealership Credit Ledger',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipClientRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_mode', models.CharField(choices=[('added_on_top', 'Added On Top'), ('deducted_from_deposit', 'Deducted From Deposit')], default='added_on_top', max_length=30, verbose_name='Fee Mode')),
                ('fee_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fee Percent')),
                ('cash_received_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cash Received from Client (IQD)')),
                ('wallet_credit_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Wallet Credit Amount (IQD)')),
                ('dealership_fee_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dealership Fee Amount (IQD)')),
                ('dealership_exposure_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Dealership Exposure Amount (IQD)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('receipt_number', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Receipt Number')),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='dealership/recharges/', verbose_name='Proof File')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Idempotency Key')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('reversal_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_recharges', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recharges', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealership_recharge', to='wallet.wallettransaction', verbose_name='Wallet Transaction')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_recharges', to='dealership.dealershipprofile')),
            ],
            options={
                'verbose_name': 'Dealership Client Recharge',
                'verbose_name_plural': 'Dealership Client Recharges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipClientCashout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount (IQD)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('code_issued', 'Code Issued'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('disputed', 'Disputed'), ('reversed', 'Reversed')], db_index=True, default='pending', max_length=20, verbose_name='Status')),
                ('confirmation_code_hash', models.CharField(blank=True, max_length=128, verbose_name='Confirmation Code Hash')),
                ('code_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Code Expires At')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmed At')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Idempotency Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('dispute_reason', models.TextField(blank=True, verbose_name='Dispute Reason')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealership_cashouts', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealership_cashout', to='wallet.wallettransaction', verbose_name='Wallet Transaction')),
                ('dealership_ledger_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_entry', to='dealership.dealershipcreditledger', verbose_name='Ledger Entry')),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_cashouts', to='dealership.dealershipprofile')),
            ],
            options={
                'verbose_name': 'Dealership Client Cashout',
                'verbose_name_plural': 'Dealership Client Cashouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipRechargeFeeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Fee (%)')),
                ('minimum_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Minimum Fee Amount (IQD)')),
                ('maximum_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Maximum Fee Amount (IQD)')),
                ('default_fee_mode', models.CharField(choices=[('added_on_top', 'Added On Top'), ('deducted_from_deposit', 'Deducted From Deposit')], default='added_on_top', max_length=30, verbose_name='Default Fee Mode')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Dealership Recharge Fee Config',
                'verbose_name_plural': 'Dealership Recharge Fee Configs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DealershipSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('total_recharges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Recharges (IQD)')),
                ('total_cashouts', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Cashouts (IQD)')),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Net Amount (IQD)')),
                ('direction', models.CharField(choices=[('dealership_owes_platform', 'Dealership Owes Platform'), ('platform_owes_dealership', 'Platform Owes Dealership'), ('settled_zero', 'Settled Zero')], max_length=30, verbose_name='Direction')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('settled_at', models.DateTimeField(blank=True, null=True, verbose_name='Settled At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dealership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='dealership.dealershipprofile')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlements_processed', to=settings.AUTH_USER_MODEL, verbose_name='Settled By')),
            ],
            options={
                'verbose_name': 'Dealership Settlement',
                'verbose_name_plural': 'Dealership Settlements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['status', 'active'], name='dealership__status_42be1a_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipprofile',
            index=models.Index(fields=['financially_locked'], name='dealership__financi_edb638_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipcreditledger',
            index=models.Index(fields=['dealership', 'transaction_type'], name='dealership__dealers_baaf05_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipcreditledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='dealership__referen_1c615e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipclientrecharge',
            index=models.Index(fields=['dealership', 'status'], name='dealership__dealers_2bc90e_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipclientrecharge',
            index=models.Index(fields=['client', 'status'], name='dealership__client__2764f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealershipclientrecharge',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('dealership_id', 'idempotency_key'), name='uq_dealership_idempotency_recharge'),
        ),
        migrations.AddIndex(
            model_name='dealershipclientcashout',
            index=models.Index(fields=['dealership', 'status'], name='dealership__dealers_a04406_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipclientcashout',
            index=models.Index(fields=['client', 'status'], name='dealership__client__434362_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealershipclientcashout',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('dealership_id', 'idempotency_key'), name='uq_dealership_idempotency_cashout'),
        ),
        migrations.AddIndex(
            model_name='dealershipsettlement',
            index=models.Index(fields=['dealership', 'status'], name='dealership__dealers_25bba7_idx'),
        ),
        migrations.AddIndex(
            model_name='dealershipsettlement',
            index=models.Index(fields=['period_start', 'period_end'], name='dealership__period__d75ed2_idx'),
        ),
    ]
