# Generated by Django 5.2.15 on 2026-06-12 08:20

import tiqani_v3.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0002_dealershipsettlement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealershipclientrecharge',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='dealership/recharges/', validators=[tiqani_v3.file_validators.validate_proof_file], verbose_name='Proof File'),
        ),
        migrations.AlterField(
            model_name='dealershipguarantee',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='dealership/guarantees/', validators=[tiqani_v3.file_validators.validate_document_file], verbose_name='Document File'),
        ),
    ]
