# Generated by Django 5.2.15 on 2026-06-12 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealership', '0003_alter_dealershipclientrecharge_proof_file_and_more'),
        ('wallet', '0003_platformfeeconfig_paymentintent_platformearning_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dealershipclientcashout',
            index=models.Index(fields=['code_expires_at', 'status'], name='idx_cashout_expiry_sweep'),
        ),
    ]
