# Generated by Django 6.0 on 2025-12-28 15:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_technicianprofile_skill_sets_and_more'),
        ('contract', '0002_contractstage_timeextensionrequest_and_more'),
        ('ratereview', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='ratereview__technic_3bb71b_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific score for communication and responsiveness', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='flagged_at',
            field=models.DateTimeField(blank=True, help_text='When the review was flagged for moderation', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times users marked this review helpful'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If false, hides the review from public listings'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='True when linked to a contract or manually approved'),
        ),
        migrations.AddField(
            model_name='review',
            name='professionalism_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific score for professionalism and conduct', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='reported_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times the review was reported'),
        ),
        migrations.AddField(
            model_name='review',
            name='technician_response',
            field=models.TextField(blank=True, help_text='Optional response from the technician'),
        ),
        migrations.AddField(
            model_name='review',
            name='timeliness_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific score for timeliness and punctuality', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, help_text='Short headline for the review', max_length=150),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='review',
            name='work_quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Specific score for quality of work', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Detailed feedback from the client'),
        ),
        migrations.AlterField(
            model_name='review',
            name='contract',
            field=models.ForeignKey(blank=True, help_text='Optional link to a contract to verify the engagement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='contract.contract'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Overall rating from 1 (poor) to 5 (excellent)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(help_text='User who submitted the review', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='technician',
            field=models.ForeignKey(help_text='Technician being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to='accounts.technicianprofile'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['technician', 'created_at'], name='ratereview__technic_6346cd_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_public'], name='ratereview__is_publ_8c2609_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified'], name='ratereview__is_veri_4501e8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['contract', 'technician'], name='ratereview__contrac_334c45_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('contract__isnull', False)), fields=('reviewer', 'contract'), name='unique_reviewer_contract_review'),
        ),
    ]
